### PR TITLE
Make clear function affect the synced data, fixes #7, fixes #13, fixes #14, fixes #17

### LINKED ISSUE #7: clear operation should be synced
The [current implementation](https://github.com/Kinto/kinto-chrome/blob/9ca6414f2fa456b79d2fe24a4baa6b2a460881c3/lib/chrome.js#L189) of `clear` only clears locally, and from then on, will only sync records that are changed afterwards. So there will be records that exist remotely but not locally.

Instead (judging from the fact that `clear` is considered a write operation by MAX_WRITE_OPERATIONS_PER_HOUR and MAX_WRITE_OPERATIONS_PER_MINUTE), it should remove (not just forget) each record in the collection.

### LINKED ISSUE #13: Deal with creation after virtual deletion
If you delete a record and then create again (without syncing inbetween), the record will exist as a tombstone in kinto.js, and creation will fail.

### LINKED ISSUE #14: area#get returns [] instead of {} when no items match

### LINKED ISSUE #17: set only sets first item
In https://github.com/Kinto/kinto-chrome/blob/f012a5122597378fe4e6f4c4a8f3b801eb52a42e/lib/chrome.js#L177-L178 all items except the first one listed are ignored.

### PR DESCRIPTION
**Pull request by michielbdejong**
- [x] Needs unit tests
- [x] Rebase once https://github.com/Kinto/kinto-chrome/pull/8 is merged

### CODE REVIEW

File: test/chrome_test.js [hunk 1]
```diff
@@ -83,22 +95,48 @@ describe("StorageArea", function() {
...
+    it("deletes all records", function(done) {
+      area.get(null, function(items) {
+        expect(items).to.deep.eql({});
+        done();
+      });
+    });
 
+    it("only deletes records virtually", function(done) {
+      area.items.list({}, { includeDeleted: true }).then(arr => {
+        console.log(arr);
```
Comment (n1k0) [inline test/chrome_test.js]: Maybe you want an assertion here

File: lib/chrome.js [hunk 2]
```diff
@@ -88,7 +88,7 @@ export class StorageArea {
 
   get(keys, callback) {
     const this_items = this.items;
-    const records = [];
+    const records = {};
```
Comment (n1k0) [inline lib/chrome.js:126]: Couldn't we use a Map here?

File: lib/chrome.js [hunk 3]
```diff
@@ -150,16 +150,23 @@ export class StorageArea {
...
+        }
         return this_items.update(record);
       }
 
-      return this_items.get(id).then(function(old_record) {return updateItem(old_record);},
-                                     function(reason) {return createItem();});
+      return this_items.get(id, { includeDeleted: true })
+      .then(function(old_record) {
+        return updateItem(old_record.data);
+      }, function(reason) {
```
Comment (n1k0) [inline lib/chrome.js]: Shouldn't we do something with the error?

File: lib/chrome.js [hunk 4]
```diff
@@ -150,16 +150,23 @@ export class StorageArea {
 
       function updateItem(old_record) {
         storage.onChanged._addChange(areaName, id, old_record, record);
+        if (old_record._status === "deleted") {
+          return this_items.delete(old_record.id, { virtual: false }).then(() => {
+            return this_items.create(record, {useRecordId: true});
+          });
```
Comment (n1k0) [inline lib/chrome.js:186]: For efficiency, could we just update `old_record` with `record` data?

File: lib/chrome.js [hunk 5]
```diff
@@ -150,16 +150,23 @@ export class StorageArea {
...
+        }
         return this_items.update(record);
       }
 
-      return this_items.get(id).then(function(old_record) {return updateItem(old_record);},
-                                     function(reason) {return createItem();});
+      return this_items.get(id, { includeDeleted: true })
+      .then(function(old_record) {
```
Comment (n1k0) [inline lib/chrome.js]: nit: indentation

File: lib/chrome.js [hunk 6]
```diff
@@ -183,7 +190,14 @@ export class StorageArea {
   }
 
   clear(callback) {
-    this.items.clear().then(function() {if (callback) {callback();}});
+    this.items.list()
+    .then(records => Promise.all(records.data.map(record =>
```
Comment (n1k0) [inline lib/chrome.js]: nit: indentation

File: lib/chrome.js [hunk 7]
```diff
@@ -183,7 +190,14 @@ export class StorageArea {
...
+      this.items.delete(record.id))))
```
Comment (n1k0) [inline lib/chrome.js]: Reasoning for not using collection.clear?

File: test/chrome_test.js [hunk 8]
```diff
@@ -70,12 +70,24 @@ describe("StorageArea", function() {
...
+      });
     });
 
-
+    it("can set a previously removed record", function(done) {
+      area.set({"something": 1}, function () {
+        area.remove("something", function() {
+          area.set({"something": 2}, function() {
+            area.get(null, function(items) {
+              console.log(items);
```
Comment (n1k0) [inline test/chrome_test.js]: We should probably remove console.log statements in tests

File: lib/chrome.js (hunk 4 above)
Comment (michielbdejong) [inline lib/chrome.js:186]: That would fail saying record not found (because it was virtually deleted)

File: lib/chrome.js (hunk 3 above)
Comment (michielbdejong) [inline lib/chrome.js]: yes, good point

File: lib/chrome.js (hunk 7 above)
Comment (michielbdejong) [inline lib/chrome.js]: We want the operation to result in all records being deleted on the server as well.

File: test/chrome_test.js (hunk 8 above)
Comment (michielbdejong) [inline test/chrome_test.js]: Oops, missed that one, thanks.

File: test/chrome_test.js (hunk 1 above)
Comment (michielbdejong) [inline test/chrome_test.js]: Oops, yes, forgot to add that.

File: lib/chrome.js (hunk 2 above)
Comment (michielbdejong) [inline lib/chrome.js:126]: No (or we would have to cast it to an `Object` later), since we need to give an ['Object with items in their key-value mappings'](https://developer.chrome.com/extensions/storage) to the callback.

File: lib/chrome.js (hunk 3 above)
Comment (michielbdejong) [inline lib/chrome.js]: done

File: lib/chrome.js (hunk 5 above)
Comment (michielbdejong) [inline lib/chrome.js]: fixed

File: lib/chrome.js (hunk 6 above)
Comment (michielbdejong) [inline lib/chrome.js]: fixed

File: test/chrome_test.js (hunk 8 above)
Comment (michielbdejong) [inline test/chrome_test.js]: removed

**Comment by michielbdejong** [comment]
@n1k0 addressed your comments, and fixed one more issue I encountered. Each commit message references the issue it fixes, but maybe you want 4 separate PRs for this?

**Comment by n1k0** [comment]
Looks all good, nits here and there r+

**Comment by michielbdejong** [comment]
Thanks! Additional comments addressed, merging.
